# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sampleAlphaPoissonCpp <- function(t, a1, b1, a2, b2, a, b, pi0, pi1, c) {
    .Call('bayesRates_sampleAlphaPoissonCpp', PACKAGE = 'bayesRates', t, a1, b1, a2, b2, a, b, pi0, pi1, c)
}

samplePowerBinomialCpp <- function(n, a1, b1, a2, b2, a, b, pi0, pi1, c) {
    .Call('bayesRates_samplePowerBinomialCpp', PACKAGE = 'bayesRates', n, a1, b1, a2, b2, a, b, pi0, pi1, c)
}

samplePowerPoissonCpp <- function(t, a1, b1, a2, b2, a, b, pi0, pi1, c) {
    .Call('bayesRates_samplePowerPoissonCpp', PACKAGE = 'bayesRates', t, a1, b1, a2, b2, a, b, pi0, pi1, c)
}

